global:
    memo: D-Elektra#0780_ICQ_TEST
default_chain: gaia
chains:
  gaia:
    key: wallet
    chain-id: GAIA
    rpc-addr: http://10.1.1.239:57122
    grpc-addr: http://10.1.1.239:59122
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01uatom
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride:
    key: wallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://10.1.1.233:57142
    grpc-addr: http://10.1.1.233:59142
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01ustrd
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
